#!/bin/bash

# Create an up-to-date EndeavourOS pacman.conf file into the current directory.
#
# Usage: go to the directory where a pacman.conf file should exist and run this script.
# Note: this script will overwrite any existing pacman.conf file in the current directory!

Main()
{
    # Remember the current directory.
    local orig_dir="$PWD"

    # Go to /tmp.
    pushd /tmp >/dev/null
    sudo pacman-key --recv-keys 8BE1FEE14302371DEF6F910A0E5877AC225D1980 --keyserver hkps://keyserver.ubuntu.com
    pacman-key --recv-keys 8BE1FEE14302371DEF6F910A0E5877AC225D1980 --keyserver hkps://keyserver.ubuntu.com
    sudo pacman-key --lsign-key 8BE1FEE14302371DEF6F910A0E5877AC225D1980
    pacman-key --lsign-key 8BE1FEE14302371DEF6F910A0E5877AC225D1980
    # Get the latest pacman.conf from Arch.
    yay -G pacman

    # Add EndeavourOS repo to pacman.conf.
    cat <<EOF >> pacman/pacman.conf

[endeavouros]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/endeavouros-mirrorlist

[Redecorating-t2]
Server = https://github.com/Redecorating/archlinux-t2-packages/releases/download/repo
SigLevel = Optional TrustAll

[arch-mact2]
Server = https://mirror.funami.tech/arch-mact2/os/x86_64
SigLever = Optional TrustAll

EOF

    # Make other adjustments in pacman.conf:
    # - add ILoveCandy
    # - enable Color, VerbosePkgLists and ParallelDownloads
    sed -i pacman/pacman.conf \
        -e '/^#Color/a ILoveCandy' \
        -e 's|^#Color|Color|' \
        -e 's|^#VerbosePkgLists|VerbosePkgLists|' \
        -e 's|^#ParallelDownloads|ParallelDownloads|'

    # Copy the updated pacman.conf to the original directory.
    cp pacman/pacman.conf "$orig_dir"/pacman.conf

    # Cleanup
    rm -rf /tmp/pacman

    # Go back to the original directory.
    popd >/dev/null
}

Main "$@"
